### ISSUE TITLE
can opentelemetry-collector send traces to langtrace?

### ISSUE THREAD

**Issue by commonfurture** [Scale3-Labs/langtrace#155]
can opentelemetry-collector send traces to langtrace?

**Comment by karthikscale3** [comment]
Hey! It should be able to send traces to langtrace. But, there is a minor bug we discovered when we tried it out. Will get this fixed in the next couple of days and let you know.

**Comment by karthikscale3** [comment]
Hi @commonfurture FYI, PR is up - https://github.com/Scale3-Labs/langtrace/pull/182/files

**Comment by karthikscale3** [comment]
@commonfurture - The support is now live on Langtrace cloud. Note: Langtrace currently accepts only json payload over http and no compression. We plan to add support for protobuf payloads and grpc soon. More docs:

https://docs.langtrace.ai/supported-integrations/otel-support/ts-http-json

Thanks for your patience
