### ISSUE TITLE
Feature Request: Disable display of prompt and response tokens to improve privacy

### ISSUE THREAD

**Issue by VfBfoerst** [Scale3-Labs/langtrace#213]
Hi :)  
  
First of all: cool project!   
  
Our company is focused on privacy, as we have the so called DSGVO in germany. We would like to use langtrace for evaluating performance, token usage, etc., but it isn't usable for us right now because it shows the prompts and response tokens in the UI, e.g.:  
![image](https://github.com/user-attachments/assets/b0c4cf1b-5023-49cc-92d1-1e7f0cc2ffcd)
  
It would be nice if we could totally disable the logging, storing, showing up of these information. So we just can analyze the rest, like token usage, performance, etc.  (-> only metrics). 
  
Idea:  
Environment Variable, e.g. METRICS_ONLY=true   
Maybe also a parameter in the python sdk which ensures that only the metrics are actually transmitted over the network so that nothing can be intercepted.  
e.g. `langtrace.init(api_key=langtrace_api_key,api_host=langtrace_url, metrics_only=True)`  
  
Thank you very much :)

**Comment by karthikscale3** [comment]
Hi @VfBfoerst , thanks for reaching out and providing some context. We can definitely prioritize this for you. Give us a couple of days and we should have a new release with this feature rolled out. I will report back here once it's live. Thanks for your patience.

**Comment by VfBfoerst** [comment]
Awesome @karthikscale3 , thank you :)

**Comment by karthikscale3** [comment]
@VfBfoerst - Please update to the latest version of the python SDK 2.2.9 and set this env var
`TRACE_PROMPT_COMPLETION_DATA=false` . Let me know if this works. This will disable capturing the content at the tracing layer so none of that data gets sent to our backend.

**Comment by VfBfoerst** [comment]
I noticed there won't be sent token counts either:  
![image](https://github.com/user-attachments/assets/a422cac6-ef8d-4d9e-b318-8b1838f8e6a4)
  
Can you reenable the token counts?  
Its just the input- and output prompts which i don't want to be logged. Despite that, I'd like to monitor/meassure the token counts.

**Comment by alizenhom** [comment]
Hey @VfBfoerst, 

i was able to replicate the same issue, after some debugging i found that the issue is ollama caches metric regarding usage tokens from the response after repeated requests

1. [this was the issue opened on ollama's repo](https://github.com/ollama/ollama/issues/2068)


the fix for me was updating ollama client to the latest version, can you try it out and tell me if it solves the issue or not would be more than happy to help!

**Comment by karthikscale3** [comment]
@VfBfoerst - Could you also pull the latest docker image for Langtrace (latest is 1.6.5). A bunch of backwards compatible changes went in and the traces view is also redesigned completely and made more user friendly. Please let us know if you face any issues.

**Comment by VfBfoerst** [comment]
@alizenhom @karthikscale3 thanks for your help :)  
I was able to try the newest version of langtrace. This seems to fix the issue. It doesn't show the prompts, but it shows input/output tokens as expected.   
![image](https://github.com/user-attachments/assets/8bd37d70-d845-46a9-ac8a-4878a5892161)
