### ISSUE TITLE
Feature Request: Support multiple API keys per project

### ISSUE THREAD

**Issue by foragerr** [Scale3-Labs/langtrace#287]
Currently, generating a new API key invalidates the existing one, making key rotation without service interruption difficult.

An ideal key rotation process would follow these steps:

- Create a new key
- Update the key in the production application
- Deactivate the old key

At a minimum, each project should support at least two active keys, though it would be preferable to allow several named keys.

**Comment by karthikscale3** [comment]
Hi @foragerr , yes, that's a limitation currently. But we are happy to prioritize adding support for 2 active keys. Will keep you posted.
