### ISSUE TITLE
Question: Ingestion limits in self-hosted?

### ISSUE THREAD

**Issue by foragerr** [Scale3-Labs/langtrace#288]
I just launched a local instance with `docker compose up` and I see this in the header.

```
Total Spans Ingested
0 out of 50,000 per month
```

Is a self-hosted installation limited to 50K ingestions per month?

**Comment by karthikscale3** [comment]
Hi @foragerr . It's not limited in the self-hosted installation. We need to get rid of that banner. You can ingest how much ever you want.

**Comment by foragerr** [comment]
Thank you,
Appreciate the quick response!
