### ISSUE TITLE
Is post hog API key required now ?

### ISSUE THREAD

**Issue by esakkiraja100116** [Scale3-Labs/langtrace#297]
### Discussed in https://github.com/Scale3-Labs/langtrace/discussions/295

<div type='discussions-op-text'>

<sup>Originally posted by **esakkiraja100116** October 14, 2024</sup>
When I saw that video you didn't configure the posthog. I thought it was optional but right i'm having validation error.
ref:
https://docs.langtrace.ai/hosting/hosting_options/docker-compose

```
Error while shutting down PostHog O [PostHogFetchHttpError]: HTTP error while fetching PostHog: 401
langtrace  |     at d (/app/.next/server/app/api/project/route.js:7:10732)
langtrace  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
langtrace  |     at async d (/app/.next/server/app/api/project/route.js:1:1879)
langtrace  |     at async $.fetchWithRetry (/app/.next/server/app/api/project/route.js:7:10536)
langtrace  |     at async $._flush (/app/.next/server/app/api/project/route.js:7:10235) {
langtrace  |   response: Response {
langtrace  |     [Symbol(realm)]: null,
langtrace  |     [Symbol(state)]: {
langtrace  |       aborted: false,
langtrace  |       rangeRequested: false,
langtrace  |       timingAllowPassed: true,
langtrace  |       requestIncludesCredentials: true,
langtrace  |       type: 'default',
langtrace  |       status: 401,
langtrace  |       timingInfo: [Object],
langtrace  |       cacheState: '',
langtrace  |       statusText: 'Unauthorized',
langtrace  |       headersList: [HeadersList],
langtrace  |       urlList: [Array],
langtrace  |       body: [Object]
langtrace  |     },
langtrace  |     [Symbol(headers)]: HeadersList {
langtrace  |       cookies: null,
langtrace  |       [Symbol(headers map)]: [Map],
langtrace  |       [Symbol(headers map sorted)]: null
langtrace  |     }
langtrace  |   }
langtrace  | }
```</div>

**Comment by esakkiraja100116** [comment]
@karthikscale3 @Dnaynu 
I resolve the about error. I used project key for post hog but still I'm not getting the logs after it got successful.
![image](https://github.com/user-attachments/assets/393e4229-11ec-4333-98db-54ce016bd2ce)

**Comment by esakkiraja100116** [comment]
can anyone help me out here ?
![image](https://github.com/user-attachments/assets/00c8d002-49f1-449e-a8d7-218c17588601)

**Comment by alizenhom** [comment]
hey @esakkiraja100116,

the endpoint for receiving traces is `http://localhost:3000/api/trace` from the screenshot i see it ends with `traces` instead of `trace`, can you try it out and let me know?

**Comment by esakkiraja100116** [comment]
Thanks a lot @alizenhom. I don't know why it's exported successfully for `/traces` since it's used only for fetch cases in frontend. 

Ref:
https://docs.langtrace.ai/hosting/using_local_setup
