### ISSUE TITLE
package import issue while trying to use with crewAI

### ISSUE THREAD

**Issue by abhaychitnis** [Scale3-Labs/langtrace#328]
I am trying to use langtrace with crewai 0.79.4. I have installed langtrace. I have edited the main.py file created by the command 'crewai create flow xxxx', as follows:
```
import os
import sys

from dotenv import load_dotenv

load_dotenv() 

from langtrace_python_sdk import langtrace # Must precede any llm module imports

langtrace.init(api_key = os.environ.get("LANGTRACE_API_KEY"))
````
I have set the environment as described in crewai documentation,
````
crewai install
source .venv/bin/activate
````
However when I run the crewai flow using
````
crewai flow kickoff
````
I get an error as follows:
````
Running the Flow
Traceback (most recent call last):
  File "/home/infdevices/research_crew/test_research_flow/.venv/bin/kickoff", line 5, in <module>
    from test_research_flow.main import kickoff
  File "/home/infdevices/research_crew/test_research_flow/src/test_research_flow/main.py", line 9, in <module>
    from langtrace_python_sdk import langtrace # Must precede any llm module imports
ModuleNotFoundError: No module named 'langtrace_python_sdk'
An error occurred while running the flow: Command '['uv', 'run', 'kickoff']' returned non-zero exit status 1.
````
The flow works correctly if the statements,
````
from langtrace_python_sdk import langtrace # Must precede any llm module imports

langtrace.init(api_key = os.environ.get("LANGTRACE_API_KEY"))
````
are removed.
I have tried to uninstall and reinstall langtrace, but it does not work.

**Comment by alizenhom** [comment]
Hey @abhaychitnis,

apologies for the issue you're facing, the issue is related to python enviroment, we are currently investigating the issue but meanwhile can you try to erase the virtual enviroment and re-create it again?

**Comment by alizenhom** [comment]
Hey @abhaychitnis, 

getting back to this, this issue appears to happen with the crewai newly added cli 
- can you confirm that you used the cli to spin up the project for example `crewai create crew <crewname>`?

if that's the case then you can just go to `pyproject.toml` and add `langtrace-python-sdk` under `dependencies` and all should work as expected

will be more than happy to address any issues if the above did not work!

**Comment by abhaychitnis** [comment]
Hi Ali
It worked. I added,
```
"langtrace_python_sdk>=3.3" 
```
to the dependencies section under [project] and it worked smoothly.

**Comment by karthikscale3** [comment]
For anyone ending up here: 
https://docs.langtrace.ai/supported-integrations/llm-frameworks/crewai#additional-setup-for-crewai-cli-projects
