### ISSUE TITLE
Updating prompt always refers to base version

### ISSUE THREAD

**Issue by lpearl** [Scale3-Labs/langtrace#343]
When updating a prompt in the prompt registry, it will always update the base prompt (e.g., version 1) instead of the most recent version or prompt version you select.

Is this the intended functionality?

**Comment by karthikscale3** [comment]
Hi, thats not an intended behavior, have you tried refreshing the page once before updating? Please let me know.

**Comment by lpearl** [comment]
No, I did not, it does seem to fix the issue. Now it only lets you update the most recent prompt version which is better.

It would be nice if you could update the prompt version you select before clicking update prompt.

Thanks for the help.

**Comment by karthikscale3** [comment]
Got it, thanks for reporting! we will get this fixed cc @alizenhom

**Comment by lpearl** [comment]
On the topic of prompts, when using zod prompts are converted to json. It would be nice if you could still edit in zod but view the prompts in json or zod. I can create a new issue but it's not that important.

**Comment by karthikscale3** [comment]
Yeah, that's definitely a great idea. We will add that feature as well. Thank you

**Comment by karthikscale3** [comment]
The PR is up - https://github.com/Scale3-Labs/langtrace/pull/344/files

**Comment by karthikscale3** [comment]
The PR is merged and release in progress. You can now:
- Update a zod schema prompt as zod schema
- Update from a previous version of a prompt and not just the latest version of the prompt
