### ISSUE TITLE
Error when cloning and running docker-compose build

### ISSUE THREAD

**Issue by DinisCruz** [Scale3-Labs/langtrace#350]
Hi, I was trying to run Langtrace locally and got this error when doing `docker compose build`

```
services.langtrace-app.depends_on.postgres-db Additional property required is not allowed
```

**Comment by alizenhom** [comment]
Hey @DinisCruz , apologies for the issue you're facing, 
can you try running `docker compose up`, you should see all services spinning up if not kindly confirm i will be more than happy to help
also do you need the build step for a specific use case?

**Comment by DinisCruz** [comment]
ok, to make it work I had to comment these:

```    restart: on-failure:5
    depends_on:
      postgres-db:
        condition: service_started
        #required: true
      clickhouse-db:
        condition: service_healthy
        #required: true
```
        
and this

```
     #start_interval: 5s
```        

I also had this weird error 

```
docker compose up                                          
[+] Running 3/0
 ⠿ Container langtrace-postgres    Created                                                                                                                                                                           0.0s
 ⠿ Container langtrace-clickhouse  Created                                                                                                                                                                           0.0s
 ⠿ Container langtrace             Created                                                                                                                                                                           0.0s
Error response from daemon: Conflict. The container name "/langtrace" is already in use by container "367ca99dc2ad6c63d9cb5241c75b4ae96c9086d7fef39b5b3beec786f1e0b316". You have to remove (or rename) that container to be able to reuse that name.
```

which was caused by

```
    restart: on-failure:5
```

starting the services manually did the trick


<img width="1204" alt="image" src="https://github.com/user-attachments/assets/e7c7497d-acf9-4ccf-95a3-e5d7197859f1">

**Comment by alizenhom** [comment]
mmm, ok i see and i think i have a theory.

if you deleted all previous images and started from scratch everything should work smoothly, kindly if you can try it out and confirm that would be great

regarding the quota - don't worry if you're self-hosting there will be no limits
