### ISSUE TITLE
AttributeError in PyPDFLoader: 'PyPDFLoader' object has no attribute 'get_num_tokens'

### ISSUE THREAD

**Issue by nachoDRT** [Scale3-Labs/langtrace#351]
**Description:**

The error occurs when attempting to load a PDF through the tools configured by CrewAI. Specifically, it seems that langtrace_python_sdk is instrumenting the method and attempting to call a non-existent method, get_num_tokens, on a PyPDFLoader object.

The issue arises in the following file:
`langtrace_python_sdk/instrumentation/langchain_community/patch.py`

In the method:

```
def traced_method(wrapped, instance, args, kwargs):
            [...]
            try: 
                # Attempt to call the original method
                result = wrapped(*args, **kwargs)
                if trace_output:
                    span.set_attribute("langchain.outputs", to_json_string(result))

                    prompt_tokens = instance.get_num_tokens(args[0])
                    completion_tokens = instance.get_num_tokens(result)
                    [...]
```

**Error Message**
`AttributeError: 'PyPDFLoader' object has no attribute 'get_num_tokens'`

**System Information**:

- Operating System: [Windows 10]
- Python Version: [Python 3.10.15]
- CrewAI Version: [0.80.0]
- LangTrace SDK Version: [3.3.4]

**Comment by alizenhom** [comment]
Thanks @nachoDRT for the descriptive message, from a quick look it should be an easy fix will replicate now and release a fix very soon will keep you posted

apologies for the issue you're facing

**Comment by alizenhom** [comment]
Hey @nachoDRT, kindly update to the latest release for python sdk [3.3.6](https://github.com/Scale3-Labs/langtrace-python-sdk/releases/tag/3.3.6)

your issue should be resolved, would be more than happy to help if you still facing any issues!

**Comment by nachoDRT** [comment]
Amazing, @alizenhom! Thank you for being so helpful and fixing it that fast! Everything is running smoothly now.

**Comment by alizenhom** [comment]
@nachoDRT Happy to help anytime!
